name: secrets

on:
  workflow_dispatch:
  pull_request:
    branches:
      - debug.*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_IS_HOGE }}
        run: |
          echo "$MY_SECRET"
