name: secrets

on:
  workflow_dispatch:
  pull_request:
    branches:
      - debug.*

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: そのまま表示
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_IS_HOGE }}
        run: |
          echo "$MY_SECRET"
### Result
# ***

      - name: '%で挟んで表示する'
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_IS_HOGE }}
        run: |
          echo "%$MY_SECRET%"
### Result
# ***

      - name: 半角スペースを入れて表示する
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_IS_HOGE }}
        run: echo "$MY_SECRET" | sed 's/./& /g'
### Result
# h o g e

      - name: catする
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_IS_HOGE }}
        run: echo "$MY_SECRET" | cat
### Result
# ***
