name: secrets

on:
  workflow_dispatch:
  pull_request:
    branches:
      - debug.*

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: そのまま表示
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_IS_HOGE }}
        run: |
          echo "$MY_SECRET"
### Result
# shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
# env:
# MY_SECRET: ***
# ***

      - name: '%で挟んで表示する'
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_IS_HOGE }}
        run: |
          echo "%$MY_SECRET%"

      - name: 半角スペースを入れて表示する
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_IS_HOGE }}
        run: echo "$MY_SECRET" | sed 's/./& /g'
